name: "Install dependencies"
description: "Installs dependencies"
runs:
  using: "composite"
  steps:
    - name: Install pnpm
      shell: bash
      run: corepack enable pnpm && pnpm -v
    - name: Setup Node.js environment
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # pin@v4.0.2
      with:
        node-version-file: ".nvmrc"
        cache: "pnpm"
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
