name: "Install dependencies"
description: "Installs dependencies"
runs:
  using: "composite"
  steps:
    - name: Install required tooling
      uses: moonrepo/setup-toolchain@c8a71c0e9bfd911b6e1caf456d3a2e3365ec86a4
      with:
        auto-install: true
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
