name: "Install dependencies"
description: "Installs dependencies"
runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2.4.0
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.1
      with:
        node-version-file: ".nvmrc"
        cache: "pnpm"
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
