# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    reviewers:
      - "R-J-dev"
    groups:
      commitlint:
        patterns:
          - "*commitlint*"
        update-types:
          - "major"
          - "minor"
          - "patch"
      eslint:
        patterns:
          - "*eslint*"
        update-types:
          - "major"
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "R-J-dev"
