name: PR validation

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

# TODO: add dependency review when this repo is public https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/configuring-dependency-review
jobs:
  format:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Validate formatting
        run: pnpm format
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Validate linting rules
        run: pnpm lint
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Test actions
        run: pnpm test:ci
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Build
        run: pnpm build
      - name: Check build
        run: |
          if ! git diff --quiet; then
            echo "Build output is different from the existing dist directory. Try running 'pnpm build' and commit the changes."
            exit 1
          fi
