name: PR validation

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

permissions:
  contents: read

# TODO: add dependency review when this repo is public https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/configuring-dependency-review
jobs:
  dependency-check:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Checking dependency licenses
        uses: ./.github/actions/license-check
      - name: Checking dependencies for security issues
        run: pnpm audit
  format:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Validate formatting
        run: pnpm format
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Validate linting rules
        run: pnpm lint
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Test actions
        run: pnpm test:ci
  build:
    needs: [dependency-check, format, lint, test]
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Build
        run: pnpm build
      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: ${{ github.event.pull_request.user.login }}
          author_email: ${{ github.event.pull_request.user.email }}
          message: "build: update build"
          add: "dist/**"
